--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nisargsc/.local/share/wallpapers/gruvbox-abstract-shapes-2-2560×1080.jpg"

-- Special
background="#181818"
foreground="#99b8b9"
cursor="#99b8b9"

-- Colors
color0="#181818"
color1="#877A6C"
color2="#679C69"
color3="#9B961A"
color4="#D89921"
color5="#928374"
color6="#B26286"
color7="#99b8b9"
color8="#6b8081"
color9="#877A6C"
color10="#679C69"
color11="#9B961A"
color12="#D89921"
color13="#928374"
color14="#B26286"
color15="#99b8b9"
