--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nisargsc/.local/share/wallpapers/reading-raccoon.jpg"

-- Special
background="#0d0c09"
foreground="#ddeef5"
cursor="#ddeef5"

-- Colors
color0="#0d0c09"
color1="#95681E"
color2="#AA6B4C"
color3="#BBA03A"
color4="#58A8A8"
color5="#C8B59C"
color6="#B7E7FB"
color7="#ddeef5"
color8="#9aa6ab"
color9="#95681E"
color10="#AA6B4C"
color11="#BBA03A"
color12="#58A8A8"
color13="#C8B59C"
color14="#B7E7FB"
color15="#ddeef5"
