# Shell variables
# Generated by 'wal'
wallpaper='/home/nisargsc/.local/share/wallpapers/reading-raccoon.jpg'

# Special
background='#0d0c09'
foreground='#ddeef5'
cursor='#ddeef5'

# Colors
color0='#0d0c09'
color1='#95681E'
color2='#AA6B4C'
color3='#BBA03A'
color4='#58A8A8'
color5='#C8B59C'
color6='#B7E7FB'
color7='#ddeef5'
color8='#9aa6ab'
color9='#95681E'
color10='#AA6B4C'
color11='#BBA03A'
color12='#58A8A8'
color13='#C8B59C'
color14='#B7E7FB'
color15='#ddeef5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
