# Shell variables
# Generated by 'wal'
wallpaper='/home/nisargsc/.local/share/wallpapers/gruvbox-abstract-shapes-2-2560×1080.jpg'

# Special
background='#181818'
foreground='#99b8b9'
cursor='#99b8b9'

# Colors
color0='#181818'
color1='#877A6C'
color2='#679C69'
color3='#9B961A'
color4='#D89921'
color5='#928374'
color6='#B26286'
color7='#99b8b9'
color8='#6b8081'
color9='#877A6C'
color10='#679C69'
color11='#9B961A'
color12='#D89921'
color13='#928374'
color14='#B26286'
color15='#99b8b9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
