# Shell variables
# Generated by 'wal'
wallpaper='/home/nisargsc/.local/share/wallpapers/lofi-samurai.jpg'

# Special
background='#151819'
foreground='#dad0dd'
cursor='#dad0dd'

# Colors
color0='#151819'
color1='#A75A6B'
color2='#69895D'
color3='#BBA85D'
color4='#5B708C'
color5='#B7709F'
color6='#67C1CD'
color7='#dad0dd'
color8='#98919a'
color9='#A75A6B'
color10='#69895D'
color11='#BBA85D'
color12='#5B708C'
color13='#B7709F'
color14='#67C1CD'
color15='#dad0dd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
